### ISSUE TITLE
Scheduler.close() takes a lot of time to finish

### ISSUE THREAD

**Issue by Fak3** [aio-libs/aiojobs#100]
I spawn many thousands of jobs to a scheduler, and after I hit ctrl-c, call `Scheduler.close()` to stop all the jobs. It takes ages to finish, because currently the job `_close()` method attempts to start its task to prevent RuntimeWarning:
```
    async def _close(self, timeout):
        self._closed = True
        if self._task is None:
            # the task is closed immediately without actual execution
            # it prevents a warning like RuntimeWarning: coroutine 'coro' was never awaited
            self._start()
```
I believe this behaivor can be optional, as I would much prefer to stop the scheduler asap, and don't care about coroutine which is never awaited.

**Comment by Dreamsorcerer** [comment]
This doesn't run the task, as it is cancelled before it has an opportunity to start.

It's the equivalent of this example:
```
import asyncio
from contextlib import suppress

async def foo():
    print("STARTED")

async def test():
    t = asyncio.create_task(foo())
    t.cancel()
    with suppress(asyncio.CancelledError):
        await t

asyncio.run(test())
```

**Comment by Dreamsorcerer** [comment]
I think you'd need to do some more thorough performance measurements to help diagnose exactly where the performance issue is, and see whether there's something we can do to improve it.
