### ISSUE TITLE
Add support for positional and keyword arguments to @atomic

### ISSUE THREAD

**Issue by Tolmachofof** [aio-libs/aiojobs#102]
I have a task to pass extra arguments in my view. 
For example:
```python
from functools import partial

from aiohttp import web
from aiojobs.aiohttp import atomic, setup


NEW, PREPARED, RESOLVED, NOT_RESOLVED = range(4)


def setup_routes(app):
    app.add_routes([
        web.post(
            r'/api/v1/tasks/{id:\d+}/to_new',
            partial(change_status, target=NEW)
        ),
        web.post(
            r'/api/v1/tasks/{id:\d+}/to_prepared',
            partial(change_status, target=PREPARED)
        ),
        web.post(
            r'/api/v1/tasks/{id:\d+}/to_resolved',
            partial(change_status, target=RESOLVED)
        ),
        web.post(
            r'/api/v1/tasks/{id:\d+}/to_not_resolved',
            partial(change_status, target=NOT_RESOLVED)
        )
    ])


@atomic
async def change_status(request, target=None):
    # Some logic depending on the target
    # ...
    return web.Response(body='Task changed status to {}'.format(target))


app = web.Application()
setup_routes(app)
setup(app)
web.run_app(app)
```
When i am using `@atomic` i get an error like:
```TypeError: wrapper() got an unexpected keyword argument 'target'```

Changes in `@atomic` can help to solve this problem:
```python
def atomic(coro):
    @wraps(coro)
    async def wrapper(request, *args, **kwargs):
        if isinstance(request, View):
            # Class Based View decorated.
            request = request.request

        job = await spawn(request, coro(request, *args, **kwargs))
        return await job.wait()
    return wrapper
```
Is it acceptable?

**Comment by obataku** [comment]
I do something similar:

`
def atomic(coro):
    """ A connexion-friendly decorator modelled after aiojobs.aiohttp.atomic """

    @wraps(coro)
    async def wrapper(*args, **kwargs):
        request = get_current_request()
        job = await spawn(request, coro(*args, **kwargs))
        return await job.wait()

    return wrapper`

**Comment by asvetlov** [comment]
I would say that `@atomic` decorator is explicitly dedicated to decorate `web-handlers` only.
In turn, the web-handler is an async function with the following signature:  `async def handler(request: web.Request) -> web.Response: ...`/
Please note: no any additional arguments, no matter if they opsitional or keyboard-only.

If you want to have them in your code -- you are doing something that doesn't conform to initial aiohttp design. 
That's fine probably, but this means that you need your own decorator instead of `@atomic`.

**Comment by obataku** [comment]
yes, I understand all that--but when using a library like connexion on top of aiohttp, the handlers no longer have such a restrictive signature (it does automatic parameter injection), e.g.

    from aiohttp.web import HTTPNotFound, json_response, Response

    @atomic
    async def delete(foo_id: str) -> Response:
        """ Delete the specified foo """
        result = await foo_service.delete(foo_id)
        return json_response(result, dumps=serializer_for(Foo).jsons) if result else HTTPNotFound()

**Comment by Dreamsorcerer** [comment]
I think we can just say that such a library is not compatible. Given the above example, we would have no idea how to get the `Request` object.

If it was done in a more explicit way with it's own decorator (so the return value from the decorator was a valid handler that can be registered on an `Application`) then it'd be a simple case of ensuring that `@atomic` is the first decorator listed.
