### ISSUE TITLE
pip install aiojobs error: <class 'FileNotFoundError'>: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiojobs#105]
[~/Documents]$ pip --verbose install aiojobs
Querying PyPI ...
Using aiojobs==0.2.2...
A binary distribution is available and will be used.
Downloading package ...
Opening: https://files.pythonhosted.org/packages/a7/8e/1d41d21e7cd09d744921490be99a9e2cfa498ae1af36b9c3ee0c3395d2c9/aiojobs-0.2.2-py3-none-any.whl

Save as: /private/var/mobile/Containers/Data/Application/106690BE-96ED-4657-8531-E99119A7CD8F/tmp//aiojobs-0.2.2-py3-none-any.whl (24664 bytes)
24664 [100.00%]
Installing wheel: aiojobs-0.2.2-py3-none-any.whl...
Extracting wheel..
Extraction finished, running handlers...
Running handler 'WHEEL information checker'...
Wheel generated by: flit 1.2.1
Running handler 'dependency handler'...
Running handler 'top_level.txt installer'...
Cleaning up...
<class 'FileNotFoundError'>: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/106690BE-96ED-4657-8531-E99119A7CD8F/tmp/wheel_tmp/aiojobs-0.2.2-py3-none-any.whl/aiojobs-0.2.2.dist-info/top_level.txt'

**Comment by yjqiang** [comment]
![image](https://user-images.githubusercontent.com/8900942/56846093-1f245480-68fd-11e9-9cc1-38a3add1138d.png)

**Comment by asvetlov** [comment]
aiojobs uses https://github.com/takluyver/flit not setuptools.
Maybe it is a bug in flit. Maybe it is fixed already, we need to check and upload new distribution files on PyPI.
Sorry, I'm pretty busy until Python 3.8 beta release.
Would you check yourself?

**Comment by yjqiang** [comment]
Looks like it should be a bug in https://github.com/ywangd/stash . Sorry to bother you and thanks a lot.
