### ISSUE TITLE
Long running task.

### ISSUE THREAD

**Issue by hound672** [aio-libs/aiojobs#107]
Hello. Is it a good idea to use it library for long running task?
For example, in web applicaton.
User makes request, server create task by scheduler.spawn and then user can request server about task's status.

**Comment by asvetlov** [comment]
Maybe.
The devil lives in details.
You *can* use aiojobs for control long running tasks, sure.
Is it optimal? Depends...

**Comment by hound672** [comment]
Ok, thanks for answer.
 Is there a way to get task's Id, to control task's status, for example for user request.

**Comment by kxepal** [comment]
>  Is there a way to get task's Id, to control task's status later?

On spawn you get Job instance which API you can use later.

As for long running tasks you will be need to do a little bit more work like respawn on failure, heartbeats and more. Current scheduler doesn't address these issues.
