### ISSUE TITLE
Way to cancel jobs when exception is raised on one of them

### ISSUE THREAD

**Issue by mprymek** [aio-libs/aiojobs#124]
Hello,

I'm trying to implement Trio-Nursery-like API on top of aiojobs Scheduler but I can't find a clean way to cancel all tasks when an exception is raised in one of them. The catch is that `exception_handler` is sync function so I can't call `await scheduler.close()` here.

I have solved it by using `asyncio.Event` and an extra task just to kill the other ones but this is not very elegant (example: https://gist.github.com/mprymek/133244919964aa18f57fbda3b55df738)

I'm not sure what the right solution would be, I see at least three possibilities:
- option to close the Scheduler when first exception occurs (implement in `Scheduler._wait_failed`?)
- make `exception_handler` async (breaking change :( )
- optional extra async exception_handler to the existing one (probably confusing)

There are probably few more...

I have not studied aiojobs source well enough to judge this and supply a PR, I'm sorry.

P.S. thanks for your work on aiojobs!

**Comment by Dreamsorcerer** [comment]
I'm assuming this is redundant with the introduction of `asyncio.TaskGroup`.
https://docs.python.org/3.11/library/asyncio-task.html#asyncio.TaskGroup
