### ISSUE TITLE
Schedule jobs from non-async code

### ISSUE THREAD

**Issue by adamrothman** [aio-libs/aiojobs#13]
Hi @asvetlov – thanks for another awesome aio library!

I was really excited to discover aiojobs as I believed it would allow me to clean up a lot of custom scheduling code I've written in my asyncio applications. Unfortunately, though, aiojobs doesn't actually support my single most-common use case: fire-and-forget background tasks.

I have lot of instances where I need to kick off an asynchronous background task *from synchronous code*. That usually ends up looking something like this:

```python
def some_sync_fn(*args, **kwargs):
    ...
    task = asyncio.ensure_future(some_async_fn('foo', 'bar', 123))
    ...
```

Obviously though this doesn't have the nice features provided by aiojobs. I got all excited to switch to aiojobs, but `Scheduler::spawn` is a coroutine – I can't call it from my sync code.

Well, that's not entirely accurate. `Scheduler::spawn` is *marked* `async`, but it never actually calls any async code:
https://github.com/aio-libs/aiojobs/blob/dd2cb0eae4d0295026b73d5fb843723aed84330a/aiojobs/_scheduler.py#L67-L81

The comment calls this out as an accommodation for possible future changes, but I would argue that this method should *never* be a coroutine. Making it so keeps consumers from scheduling background tasks from their sync code, which is (IMO at least) one of the major features a scheduler should offer. Is there something you have in mind for the future that requires `spawn` to be a coroutine?

Although I think it makes more sense for `spawn` to simply stop being a coroutine, I'd even settle for a different `Scheduler` method that sets up the task and returns immediately.

What do you think?

**Comment by asvetlov** [comment]
Sorry, I though I had answered already.

Converting from coroutine to non-coroutine and back is painful process.
Making the method a coroutine prevent the pain if in future we will decide to do more work on spawning.

Also changing a method signature after publishing is impossible -- it breaks all existing code.
But I suggest adding a new synchronous method like `sync_spawn()`. Documentation should explicitly encourage using of `spawn()` from coroutines and call `async_spawn()` from synchronous code only.

If you like the idea -- please make a Pull Request.

**Comment by adamrothman** [comment]
#15 😄

**Comment by adamrothman** [comment]
#16 😄

**Comment by asvetlov** [comment]
Close.
See #16 for the reason
