### ISSUE TITLE
Deprecation warnings in asyncio with Python 3.8

### ISSUE THREAD

**Issue by dmajda** [aio-libs/aiojobs#137]
When using aiojobs with Python 3.8 with warnings enabled, deprecation warnings are emitted at various places where a `loop` argument is passed to `asyncio` APIs. This is because explicit passing of that argument was deprecated and will be removed in Python 3.10. For some of the warnings, see for example [this Travis CI build](https://travis-ci.com/aio-libs/aiojobs/jobs/256875593).

It would be good to fix these warnings. Looking at the code, it seems like the most sensible course of action would be to stop passing the `loop` argument to `Job` and `Scheduler` and just switch them to `asyncio.get_running_loop()` (with a `asyncio.get_event_loop()` fallback for Python < 3.7).

**Comment by asvetlov** [comment]
Your detection is correct.
I have no estimation when I'll have time for this task.
Any help is welcome.

Small implementation note: please follow the pattern from [async-timeout](https://github.com/aio-libs/async-timeout/blob/master/async_timeout/__init__.py#L212-L219) for `get_running_loop()` / `get_event_loop()` using.

**Comment by Dreamsorcerer** [comment]
Appears to have been fixed.
