### ISSUE TITLE
Why python >= 3.5.3 ?

### ISSUE THREAD

**Issue by NotSqrt** [aio-libs/aiojobs#14]
Hi,

Is there a reason for the `python_requires='>=3.5.3'` ?
Python 3.5.2 is the default for ubuntu LTS 16.04 for instance.

Was there a fix in python between 3.5.2 and 3.5.3 ?

Thanks !

**Comment by asvetlov** [comment]
In 3.5.3 `asyncio.get_event_loop()` always returns a running event loop instance.
It's crucial for working with implicit loop only.
Could deadsnakes https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes satisfy your needs?
It allows to setup even Python 3.6 AFAIK

**Comment by kxepal** [comment]
Indeed it provides Python 3.6.

**Comment by NotSqrt** [comment]
Too bad that deadsnakes does not provide python 3.5.3 or 3.5.4 for Xenial ..

Thanks for the explanation.

**Comment by asvetlov** [comment]
I pretty sure you can run your project on Python 3.6 without issues (or in worst case it takes a half hour for migration).
