### ISSUE TITLE
CancelledError are not handled correctly even with aiojobs

### ISSUE THREAD

**Issue by larry-dev** [aio-libs/aiojobs#18]
We are running a internet mobile app which has around 100,000 users accessing each day . Probably，the web server received 3,000 hits per second.
Since all the user access should be realtime mode . We use aiohttp framework to handle all of them.
Every sec, the error log records around 5,6 cancellederrors which confused us very much . We can not figure out the real cause why so many cancellederrors are threw .
After several rounds of discussion in GitHub , we got to know the version of aiohttp 2.3.0 has resolved this common problem by using aiojobs to reduce the number of cancellederror occured.
But after 2.3.0 implemented ， nothing has been changed. the number of cancellederror still remains same.

The error will cause the saving to the redis failed , while errors accumulated in certain amount , all the operations to redis will be responsed "error" .

It suffers. and we hope to have a good solution to cater it to get rid of all the cancellederror.

[The more information are in the thread which were just moved from aio-libs/http] (https://github.com/aio-libs/aiohttp/issues/2466)
We are actually losing data in redis
And we also get many errors loged, 
Plus our service was shutdown.

**Comment by asvetlov** [comment]
As I wrote in aio-libs/aiohttp#2374 socket.io library should handle cancellation properly.

**Comment by larry-dev** [comment]
Thx a lot @asvetlov
