### ISSUE TITLE
Add a new scheduler parameter for control pending jobs size

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiojobs#19]
`await scheduler.spawn(...)` should wait if too many pending jobs are scheduled.

**Comment by 1oomis** [comment]
From your comment to PR #16 : spawn_nowait should raise an exception if too many pending jobs.
Seems like you want `self._pending` act like a standard `asyncio.Queue`
where `await q.put(item)` waits until a free slot is available and `q.put_nowait(item)` raises QueueFull exception.
Is it necessary to use `deque` for `self._pending` ?

**Comment by asvetlov** [comment]
Technically no. `asyncio.Queue` with limited size should work fine.

**Comment by asvetlov** [comment]
Fixed by #24
