### ISSUE TITLE
Upgrade to 0.4.0

### ISSUE THREAD

**Issue by Skorpyon** [aio-libs/aiojobs#20]
Please upgrade lib to 0.4.0 because PyPI version 0.3.0 doesn't contain `aiojobs.aiohttp.atomic` decorator

**Comment by asvetlov** [comment]
aiojobs 0.1.0 released

**Comment by takebayashi** [comment]
@asvetlov v0.1.0 seems to not be available at [PyPI](https://pypi.python.org/pypi/aiojobs).
Could you please publish it?

**Comment by asvetlov** [comment]
Done
