### ISSUE TITLE
How to call my 'non asyncio' class from aiojobs

### ISSUE THREAD

**Issue by binooetomo** [aio-libs/aiojobs#228]
Dear All.

I just jump'n to async world.
I need to fetch metrics from some host.
Currently I work it in sync way.
Every single loop (fetching 32 host) will take +/- 20 secs.
That is, for each host I only got new metric every 20 secs.

I need to got metric (for each host) every 1 sec.

Here is my noodle script:

    #!/usr/bin/env python

    import os
    import sys
    import datetime, time
    import traceback
    import json
    import logging
    import configparser

    import json
    import uuid
    import websocket

    import asyncio
    import aiojobs

    class xo:
        def __init__(self, server, email=None, password=None):
            self._server = server + '/api/'
            self._email = email
            self._password = password

            self._ws = websocket.WebSocket()
            self._ws.connect(self._server)
            payload = {
                "method": "session.signInWithPassword",
                "params": {"email": self._email, "password": self._password},
                "jsonrpc": "2.0",
                "id": uuid.uuid1().hex
            }
            resp=self.call(payload)

        def call(self,payload,timeout=10):
            self._ws.send(json.dumps(payload))
            start_time = time.time()
            resp = None
            while time.time() < (start_time + timeout):
                resp = json.loads(self._ws.recv())
                if ('id' not in resp) or resp['id'] != payload['id']:
                    resp = None
                    continue
                else:
                    break
            return resp

        def getAllHost(self):
            payload = {
                "method": "xo.getAllObjects",
                "params": {'filter':{'type':'host'}},
                "jsonrpc": "2.0",
                "id": uuid.uuid1().hex
            }

            resp=self.call(payload)
            return resp['result']

        def getHostStat(self,id):
            payload = {
                "method": "host.stats",
                "params": {'host':id},
                "jsonrpc": "2.0",
                "id": uuid.uuid1().hex
            }
            resp=self.call(payload)
            return resp['result']

        def getAllStat(self):
            hosts=self.getAllHost()
            for k,v in hosts.items():
                hosts[k]['stat']={'error':None, 'data':None}
                try :
                    hosts[k]['stat']['data']=self.getHostStat(k)['stats']
                except Exception as e :
                    hosts[k]['stat']['error']=str(e)

            return hosts

    async def coro(seq,id,rawstat):
        print('Start Of {} / {} at {}'.format(rawstat['name_label'], seq,time.time()))
        try :
            stats = myxo.getHostStat(id)
        except Exception as e:
            pass
        print('\t End Of {} / {} at {}'.format(rawstat['name_label'], seq,time.time()))

    async def main():
        scheduler = await aiojobs.create_scheduler()
        rawhosts=myxo.getAllHost()
        seq=0
        while True :
            for k,v in rawhosts.items():
                await scheduler.spawn(coro(seq,k,v))
            await asyncio.sleep(1.0)
            seq+=1

    if __name__ == '__main__':
        iniconfig = configparser.ConfigParser()
        try :
            iniconfig.read(sys.argv[1])
            print('Using config from: {}'.format(sys.argv[1]))
        except Exception as e:
            try :
                iniconfig.read('./xostat.ini')
                print('Using config from: ./xostat.ini')
            except Exception as e:
                sys.exit('No configuration file defined/found')

        #Init Connection to XO-Server
        try :
            wsuri='ws://{}:{}'.format(iniconfig['xo']['address'],
                iniconfig['xo'].get('port',80))
            wsuser=iniconfig['xo']['user']
            wspwd=iniconfig['xo']['password']
        except Exception as e :
            sys.exit('Wrong formated config file')

        myxo=xo(wsuri,wsuser,wspwd)

        asyncio.get_event_loop().run_until_complete(main())

and the sniped result :

    Using config from: ./xostat.ini
    Start Of Kalingga / 0 at 1608360338.888853
	     End Of Kalingga / 0 at 1608360339.4845614
    Start Of Jayabaya / 0 at 1608360339.4847863
	     End Of Jayabaya / 0 at 1608360339.821991

    ... (and bunch of it)

    Start Of Kalingga / 1 at 1608360366.2312956
	     End Of Kalingga / 1 at 1608360367.1854613
    Start Of Jayabaya / 1 at 1608360367.1857102
	     End Of Jayabaya / 1 at 1608360367.476213

Note that there is still 28 secs delay between 1st start of kalingga and 2nd star of kalingga.
Event that a single fetch of kalingga only take +/- 1 sec.

Kindly please tell me how to make my script run fully async.

Sincerely
-bino-

**Comment by webknjaz** [comment]
Looks like you're trying to execute a long-running synchronous process. These completely block the IO loop, stopping any async code until that synchronous chunk gets returns. You could attempt running that in a separate thread or process with https://docs.python.org/3/library/asyncio-eventloop.html#executing-code-in-thread-or-process-pools.

**Comment by binooetomo** [comment]
@webknjaz
I appreciate your response.

Hmmm thats a new magic.
I'll try to rewrite my sycn class to use asyncio first.
