### ISSUE TITLE
Plans to integrate thread pool executor/process pool executor (potentially aioprocessing?)

### ISSUE THREAD

**Issue by CMCDragonkai** [aio-libs/aiojobs#235]
I think aiojobs can be quite a useful abstraction for any usage of asyncio for long-running tasks (or tasks that live longer than a single request-response lifetime when used with aiohttp).

However aiojobs currently does talk at all about the usage of threads and/or processes.

It would be really helpful if aiojobs integrated some native form of threading using threadpoolexecutor or processpoolexecutor.

The `aioprocessing` library can be a starting point for using a process pool.

Imagine being able to create the aiojobs scheduler while specifying different executor. Default executor might be just part of the same asyncio loop. Optionally a threaded executor and optionally a process executor.

That way I might create 3 aiojobs schedulers if I have a complex aiohttp application that sometimes requires running jobs that need to live past a single request/response lifecycle, sometimes running jobs that needs to make use of IO-parallelism, and sometimes running jobs that needs to make use of CPU-parallelism.

Here's and example of using asyncio with threadpool and processpool executors: https://gist.github.com/jmbjorndalen/e1cbd93c475792c83f79ef475345ed00

**Comment by Dreamsorcerer** [comment]
I think your best option is to just schedule an async function which does something like `await asyncio.to_thread(...)`. This seems simple enough to me, plus avoids adding a load of extra complexity to the library.
