### ISSUE TITLE
Cancel on waiting jobs should be protected

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiojobs#25]
Example:

```python
from aiohttp import web
from aiojobs.aiohttp import setup, spawn

async def handler(request):
    await spawn(request, coro())
    return web.Response()

app = web.Application()
app.router.add_get('/', handler)
setup(app)
```

Cancellation of `await spawn(request, coro())` by https://github.com/aio-libs/aiohttp/pull/2257/files should be covered by `asyncio,shield` or custom wrapper

As well aiohttp docs for now can use combination of `asyncio.shield` and `spawn` to illuminate unexpected behavior

**Comment by asvetlov** [comment]
`@atomic` should be protected and it is after #28
In contrast cancelling `spawn()` call means that waiting for a free slot in pending queue was not successful, outer task was closed earlier.

I don't think we have do something here, in practice cancelling on `await spawn()` could be processed as connection lost *before* `spawn()` call -- from web server perspective should be no difference.
