### ISSUE TITLE
Missing type annotations.

### ISSUE THREAD

**Issue by DriesSchaumont** [aio-libs/aiojobs#303]
Hi,

I am using `aiojobs 1.0.0`, which added support for type hint checking (see #280).
However, there seem to be several functions missing type annotations which are causing errors when using mypy with `disallow_untyped_calls = true`. As an example, for `setup` I seem to be getting:
`error: Call to untyped function "setup" in typed context`

I was wondering if any efforts will be made to add type annotations for all public API elements?

Thanks!

**Comment by pollydrag** [comment]
Seems to have been fixed in #352
