### ISSUE TITLE
Package feature

### ISSUE THREAD

**Issue by AIGeneratedUsername** [aio-libs/aiojobs#320]
Is the package maintained? I mean that the Pull requests count is growing.
If it is not actively maintained, maybe you will give someone a "write" permission so someone will be able to review and merge pull requests?

I understand that a maintainer doesn't owe anything to anybody, so keeping a stable 1.0 version for years without updates for new Python versions is fine. I just want to add some clarity here so other people may build their plans.

**Comment by Dreamsorcerer** [comment]
I've started watching activity on the repo, so will be happy to review any further PRs.

**Comment by AIGeneratedUsername** [comment]
> I've started watching activity on the repo, so will be happy to review any further PRs.

@Dreamsorcerer Do you have a permission to publish a new package version on PyPi? As I remember, there were some bugs that were fixed recently (or will be), so it will be great to publish a new package version.

**Comment by Dreamsorcerer** [comment]
Try to replace the build system with setuptools to match all our other repos. Will try a release after.
