### ISSUE TITLE
Add name param to spawn

### ISSUE THREAD

**Issue by dave-fitzgerald-bc** [aio-libs/aiojobs#324]
## Feature request:

I would like to be able to use the scheduler API to set and get task/job names. Something like so:

### Proposed Usage

```python
await scheduler.spawn(my_task(), name="my-task")
await scheduler.spawn(another_task(), name="another-task")

jobs = [job for job in scheduler._jobs]
task_names = [job._task.get_name() for job in jobs]
```
### Output:
```
task_names
> ['my-task', 'another-task']
```

### Bonus Usage

Even better would be delegating `job.get_name()` to `job._task.get_name()` so the final usage could be like:

```python
job_names = [job.get_name() for job in scheduler._jobs]
```
### Output:
```
job_names
> ['my-task', 'another-task']
```

At the moment if I needed to get the task name I would have to use the following and I'd rather not access so many private variables if possible:

```python
task_names = [job._coro.cr_code.co_name for job in scheduler._jobs]
```

**Comment by Dreamsorcerer** [comment]
I think we could pass the `name` parameter to `asyncio.create_task()` somehow and then maybe add a helper method to also fetch the name.

Feel free to make a PR.

**Comment by dave-fitzgerald-bc** [comment]
Thanks @Dreamsorcerer & @zoicsoftware for your time and effort
