### ISSUE TITLE
graceful shutdown -- wait for all jobs to finish

### ISSUE THREAD

**Issue by explosic4** [aio-libs/aiojobs#35]
I am using aiohttp, and I am using spawn to execute some atomic process in the background. I wonder how can I wait for all jobs to finish before I shutdown the aiohttp server.

Currently, I am using the following code:
```py
async def shutdown(app):
    jobs = get_scheduler_from_app(app)._jobs
    while True:
        await asyncio.sleep(0)
        if len(jobs) == 0:
            return

app.on_shutdown.append(shutdown)
```

I am not sure wether it's a good/correct way to do that. I hope there will be a method like `scheduler.wait_for_close()` to do it.

PS: I didn't set the limit or the pending limit for the scheduler yet, I know there is a job queue and a pending queue, I'm not sure wether that will affect my code above.

**Comment by asvetlov** [comment]
You've reinvented [Scheduler.close](https://aiojobs.readthedocs.io/en/stable/api.html#aiojobs.Scheduler.close) with infinite `close_timeout` :)

**Comment by explosic4** [comment]
Could you explain how `Scheduler.close` and `job.close` Works?

```py
# scheduler.close
    async def close(self):
        if self._closed:
            return
        self._closed = True  # prevent adding new jobs

        jobs = self._jobs
        if jobs:
            # cleanup pending queue
            # all job will be started on closing
            while not self._pending.empty():
                self._pending.get_nowait()
            await asyncio.gather(
                *[job._close(self._close_timeout) for job in jobs],
                loop=self._loop, return_exceptions=True)
            self._jobs.clear()
        self._failed_tasks.put_nowait(None)
        await self._failed_task
```

Here is my guess for how `scheduler.close` works :
1. first empty the pending queue, which means jobs in pending queue won't be executed.
2. then it waits for the jobs to close with a close timeout.
3. finally it processes the exception raised by failed tasks


```py
# job._close
    async def _close(self, timeout):
        if self._closed:
            return
        self._closed = True
        if self._task is None:
            # the task is closed immediately without actual execution
            # it prevents a warning like
            # RuntimeWarning: coroutine 'coro' was never awaited
            self._start()
        if not self._task.done():
            self._task.cancel()
        # self._scheduler is None after _done_callback()
        scheduler = self._scheduler
        try:
            with async_timeout.timeout(timeout=timeout,
                                       loop=self._loop):
                await self._task
        except asyncio.CancelledError:
            pass
        except asyncio.TimeoutError as exc:
            if self._explicit:
                raise
            context = {'message': "Job closing timed out",
                       'job': self,
                       'exception': exc}
            if self._source_traceback is not None:
                context['source_traceback'] = self._source_traceback
            scheduler.call_exception_handler(context)
        except Exception as exc:
            if self._explicit:
                raise

            self._report_exception(exc)
```
And my guess for how `job.close` works:

It starts the job and then cancels it immediately, and then waits for it to cancel within the timeout, if the job is not canceled within the timeout, it raises the exception and reports it.

So if my guess is correct, in order to use  `scheduler.close()`,  I need to handle the `CancelError` myself, and set a larger timeout?

**Comment by asvetlov** [comment]
You are correct.
`CancelledError` is not passed to `.close()` the caller, the method is exception-free.

**Comment by explosic4** [comment]
Well, I don't want to send `CancelledError` to my jobs and handle it manually, I want to wait for the jobs to finish and then close the scheduler, thus I don't want to use `.close()`. 

I will stick with my method for the time being.

**Comment by asvetlov** [comment]
Use at least `len(scheduler)`.
But I pretty sure that close timeout (maybe very big though) is necessary -- otherwise you can get into a trap of infinite waiting.
