### ISSUE TITLE
question: aiojobs, asyncio.to_thread(), and streamlit

### ISSUE THREAD

**Issue by v1gnesh** [aio-libs/aiojobs#358]
Hello,

Firstly, thanks to everyone who make extremely useful projects like these, open source.

There's a use case I want to understand better, hope I've explained it ok below.
Say I have a [streamlit](https://streamlit.io/) app that's like this:

```python
import asyncio
import streamlit as st
from datetime import datetime

async def watch(t: st._DeltaGenerator):
    while True:
        t.markdown(f"""{str(datetime.now())}""")
        await asyncio.sleep(1)

test = st.empty()
asyncio.run(watch(test))
```

Assume that instead of `datetime.now()` I have code to repeatedly countdown from 10 to 0 seconds.
I have another coro that does a bunch of `aiohttp` and takes 5-6s to run.
We can consider this aiohttp coro blocking io because I need its result when countdown hits 0, to refresh the streamlit page.
So when the countdown hits 6, I want to start the aiohttp coro, in a way that I don't block `watch`, which is the main `streamlit` app.
If I just do `await aiohttp_coro` when the countdown hits 6, it freezes the main thread.

For this, I see that from python 3.9, there is `asyncio.to_thread()`.
Say I do:
```python
if interval == 5:
  data = await asyncio.to_thread(aiohttp_coro())
elif interval == 0:
  interval = 10
  t.json(data)
```

... will this still block my main `watch` thread?

Second, for a small case like this, is it apt to use `asyncio.to_thread()`, or will `aiojobs` be a better fit?

And fInally, I hope aiojobs will be updated over time to add support for TaskGroup (from python 3.11 onwards)?

Thanks for your time!

**Comment by Dreamsorcerer** [comment]
I think your question is just about how to write asyncio code, not actually anything to do with aiojobs.

But, to summarise, `await` asks the code to wait for the result of a coro, and so execution won't go past that line until the coro has completed. It that respect, it is similar to make a normal function call (you should be able to understand that your code wouldn't work if you had just done `requests_func()` with a non-async function).

There are a few ways to run a task in parallel, but the method you probably want here is `asyncio.create_task()`, which will schedule the coro as a task to run in the event loop. Your code looking something like:
```
for i in range(10, -1, -1):
    print(i)
    if i == 6:
        t = asyncio.create_task(run_aiohttp())
    await asyncio.sleep(1)
await t
```

Notice the final `await t` which both ensures the task is complete (it will wait on it if not already finished) and also makes sure any exceptions or anything in the task are raised (without that line you would get a warning about an unawaited task).

`asyncio.to_thread()` is *not* something you should be using for this kind of task.


In another situation, where you just want to run multiple tasks together at the same time, you would want to make use of `asyncio.gather()`.

`aiojobs` is about throwing tasks into the background. i.e. It handles the case where you want to do `asyncio.create_task()`, then end your current function without `await`ing on that task. In this case, `aiojobs.Scheduler` will manage the lifetime of the task and ensure the task is awaited correctly when it is complete and log any exceptions.
    An example case would be in your web handler, you want to trigger a long-running task in response to the request, but return a response to the user and close the connection immediately, leaving that task running in the background.

> And fInally, I hope aiojobs will be updated over time to add support for TaskGroup (from python 3.11 onwards)?

I'm not sure what you expect it to do in regards to `TaskGroup`. Hopefully the above explanation will have improved your understanding. If you still think there's something to do with `TaskGroup` then please explain further.

**Comment by Dreamsorcerer** [comment]
Alternative approach with TaskGroup:
```
async with asyncio.TaskGroup() as tg:
    for i in range(10, -1, -1):
        print(i)
        if i == 6:
            t = tg.create_task(run_aiohttp())
        await asyncio.sleep(1)
```

But, if you're only creating 1 task, seems a bit pointless to use `TaskGroup`.

**Comment by v1gnesh** [comment]
Thanks for your detailed comments.

About `TaskGroup`, it was just a general question on how/whether `aiojobs` will internally benefit from the availability of `TaskGroup`. 

About the main question... my `run_aiohttp()` is roughly this:

```python
out1 = await another_coro1()
out2 = await another_coro2(out1)
```

There are further for loops in `another_coro2()` to create tasks and gather their outputs.

The problem with `await t` from that example is that it'll lock up the main event loop.
In the main event loop, I just want the countdown from the for loop printed out (to say next page refresh in 9..8..7..1s).
And when I hit 6s, I want to initiate `run_aiohttp()` in the background (because I know it will take ~6s to complete).
So when the main countdown hits 0s, I'll have the output from `run_aiohttp()` in hand to output in the main event loop (the `streamlit` page).

So `to_thread()` does seem to fit the bill; just wanted to clarify if I'm on the right track with this.
And if I can replace `to_thread()` with `aiojobs` / its scheduler if I need to do more stuff off of the main event loop.

I hope this explanation helps clarify what I'm trying to do. I do use `gather` and `create_task` a whole bunch.
The short of it is... the main loop's countdown can be blocking 'io', but the `run_aiohttp()` should be non-blocking, i.e., don't want to use `await` in the main loop freezing the page. The 10-to-0 countdown will be a forever loop, i.e, 10..9..1..0..10..9.. etc.

**Comment by Dreamsorcerer** [comment]
> About `TaskGroup`, it was just a general question on how/whether `aiojobs` will internally benefit from the availability of `TaskGroup`.

I'm still not sure it's relevant. What benefit would it add?

> The problem with `await t` from that example is that it'll lock up the main event loop. In the main event loop, I just want the countdown from the for loop printed out (to say next page refresh in 9..8..7..1s). And when I hit 6s, I want to initiate `run_aiohttp()` in the background (because I know it will take ~6s to complete). So when the main countdown hits 0s, I'll have the output from `run_aiohttp()` in hand to output in the main event loop (the `streamlit` page).

No, the `await t` is after the loop, so it can't be blocking the loop... If your function takes <6s then it won't block at all, as the result will already be there.

> So `to_thread()` does seem to fit the bill; just wanted to clarify if I'm on the right track with this.

Again, `asyncio.to_thread()` is **not** the right solution for your case. You just need to get a better understanding of tasks and the asyncio functions available to manage their lifecycle. In fact, in this case, it would probably behave almost exactly like `await coro()`.

> I hope this explanation helps clarify what I'm trying to do. I do use `gather` and `create_task` a whole bunch. The short of it is... the main loop's countdown can be blocking 'io', but the `run_aiohttp()` should be non-blocking, i.e., don't want to use `await` in the main loop freezing the page. The 10-to-0 countdown will be a forever loop, i.e, 10..9..1..0..10..9.. etc.

If it's looping indefinitely, you can always check `Task.done()` before trying to `await` on it. Using aiojobs might be a valid option in this case if you just want to fire-and-forget the tasks. A fuller example of your code is probably needed if you want further tips.

**Comment by v1gnesh** [comment]
> I'm still not sure it's relevant. What benefit would it add?

Submitting named, grouped tasks?

On the main topic... sample code & its output:

```python
import asyncio


async def run_aiohttp():
    print('yeh')
    await asyncio.sleep(6)
    print('fin')


async def func():
    global t
    for i in range(10, -1, -1):
        print(i)
        if i == 6:
            t = asyncio.create_task(run_aiohttp())
        await asyncio.sleep(1)
    await t


if __name__ == "__main__":
    asyncio.run(func())
```


```
10
9
8
7
6
yeh
5
4
3
2
1
fin
0

Process finished with exit code 0
```

> No, the await t is after the loop, so it can't be blocking the loop... If your function takes <6s then it won't block at all, as the result will already be there.

As you've said, `create_task` seems to be sufficient. Don't understand why this works though.
Doesn't having `await t` after the loop mean that it only starts executing and getting the output then?
Or is it that `create_task` itself will kick it off, and `await` is just where I collect the output?

> In fact, in this case, it would probably behave almost exactly like await coro().

Just tested, and you're right of course.
Using `asyncio.to_thread(run_aiohttp())` instead of `asyncio.create_task(run_aiohttp())` makes the loop wait for 6s after printing '6'.

**Comment by Dreamsorcerer** [comment]
> > I'm still not sure it's relevant. What benefit would it add?
> 
> Submitting named, grouped tasks?

Umm, maybe I'm misunderstanding something, but how would you do that? What would the interface look like?

> Doesn't having `await t` after the loop mean that it only starts executing and getting the output then? Or is it that `create_task` itself will kick it off, and `await` is just where I collect the output?

The latter. As I mentioned previously, `create_task()` creates a task from the coro and schedules it in the event loop to run (so, it will actually run when you yield at `await asyncio.sleep(1)` on the next line).
`await t` is only there to ensure the value/exception is handled correctly, it will also wait for the task to complete if it has not already finished.

**Comment by v1gnesh** [comment]
As you've found, I had a gaping hole in my understanding about `async/await` (Thanks for clearing that up!).

So when I'm asking about `TaskGroup` for `aiojobs`, it's more from curiosity than from knowing something with conviction.
I'm just wondering if spawning jobs into a `TaskGroup` (also `ExceptionGroup`) will be useful for organising status info & such. Might come in handy when printing traceback.

Also, when JetBrains decides to complete its debug/profiling implementation for python's async, task groups & named tasks will help draw clean swimlanes.

**Comment by Dreamsorcerer** [comment]
`TaskGroup` is not something you pass around. If you look at the examples, you run it like:
```
async with TaskGroup() as tg:
    tg.create_task(...)
```
When you exit the `async with` block, any unfinished tasks will be waited on (like our `await t` above). So, if you tried to pass `tg` to aiojobs, it wouldn't make sense, because the tasks would already have completed.

Just think of `TaskGroup` and `aiojobs.Scheduler` as alternative methods for running tasks.
The former allows you to ensure they are all completed at a given point in the code (without needing to keep track of all the created tasks and `asyncio.gather()` them at the end). The latter allows you to fire-and-forget tasks into the background when you have no interest in awaiting the results.

**Comment by Dreamsorcerer** [comment]
> Also, when JetBrains decides to complete its debug/profiling implementation for python's async, task groups & named tasks will help draw clean swimlanes.

#324 is a request for using the `name` parameter for named tasks. But, as mentioned, `TaskGroup` is not about grouping tasks or giving them a namespace, it is just about scheduling and awaiting on those tasks.

**Comment by v1gnesh** [comment]
Thanks again for taking the time to explain. Really appreciate it!
