### ISSUE TITLE
tests dir included to whl

### ISSUE THREAD

**Issue by DmitryKuk** [aio-libs/aiojobs#437]
Hello!

After debugging some imports in my project I found that `aiojobs-1.1.0-py3-none-any.whl` ships `tests/` directory to my site-packages. Wheel content is:
- aiojobs/
- aiojobs-1.1.0-dist-info/
- tests/

It leads to:
```
>>> import tests
>>> tests.__file__
'/path/to/my_venv/lib/python3.11/site-packages/tests/__init__.py'
```

This behaviour looks incorrect. My project (and not only it) has `tests/` directory too, so project unit tests are broken. Please note, `aiojobs-1.0.0-py3-none-any.whl` has no `tests/` inside.

I think possible solution should be like this: https://github.com/googleapis/python-org-policy/pull/121/files (from this issue: https://github.com/googleapis/python-org-policy/issues/120).

**Comment by DmitryKuk** [comment]
Tried to reproduce this build on current `master`, but got wheel without `tests/`.
![image](https://github.com/aio-libs/aiojobs/assets/6614548/fef8cdce-da36-4a90-99d4-77c5755834aa)

**Comment by DmitryKuk** [comment]
Wheel with `tests/` reproduced, when building after:
`git checkout tags/v1.1.0`

Maybe, it's already fixed.
Can you please publish new release to allow using fixed version without building manually?

**Comment by ikornaselur** [comment]
This was fixed in #408 but not yet released, very much in favour of a new release because of this :pray:

**Comment by DmitryKuk** [comment]
Good news, thank you!:)
Going to close this issue as duplicate of already implemented fix...

**Comment by Dreamsorcerer** [comment]
Done

**Comment by DmitryKuk** [comment]
Thanks a lot!!!
