### ISSUE TITLE
Nested applications do not resolve the scheduler set on a parent application

### ISSUE THREAD

**Issue by mrasband** [aio-libs/aiojobs#51]
As expected, not all attributes cascade from parent apps to nested apps. However aio-libs/aiohttp@SHA:fb0106a added support for a request to resolve parent app config that should be leveraged to share a scheduler across apps by default, but allow each app to have their own if necessary.

**Comment by mrasband** [comment]
I can submit a PR for this, but wanted to ask: Should `aiohttp.get_scheduler_from_app` be retained, or can that be moved to `aiohttp.get_scheduler_from_request` and utilize `request.config_dict.get('AIOJOBS_SCHEDULER')`

**Comment by asvetlov** [comment]
`request.config_dict` is a new API, you need a new function for aiojobs too.
Docs and tests are required :)
