### ISSUE TITLE
Why aiojobs is depended on aiohttp?

### ISSUE THREAD

**Issue by kxepal** [aio-libs/aiojobs#53]
This seems happened during migration to flit at https://github.com/aio-libs/aiojobs/commit/78cd035867285706c999b5bec1be2c0511c02753

While aiojobs provides some handy integration with aiohttp, it seems strange that it depends on it. What if we would like to use aiojobs without aiohttp? Is it still a case?

**Comment by asvetlov** [comment]
It could be `requires-extra`.
Would you make a PR?
Docs update is needed to reflect the change.

**Comment by kxepal** [comment]
Ok, will do it. I was wondering if that is intentional or not.

**Comment by asvetlov** [comment]
Fixed by #80
