### ISSUE TITLE
Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by quancore** [aio-libs/aiojobs#61]
**Function call:**
`asyncio.get_event_loop().run_until_complete(self.distrubute_jobs())`
**Functions:**
![image](https://user-images.githubusercontent.com/15036825/46535666-71901c00-c8ac-11e8-9ca9-bb509d84407d.png)
**Error:**
![image](https://user-images.githubusercontent.com/15036825/46535720-8f5d8100-c8ac-11e8-8a7d-17417ddcc296.png)

**Comment by st4lk** [comment]
I had a similar behavior when I didn't call
```python
await scheduler.close()
```

Once I've done it - the error was gone.

**Comment by quancore** [comment]
Yes I have already did it, thanks for your command.
