### ISSUE TITLE
Documentation should explain what "closing" a job means

### ISSUE THREAD

**Issue by gjcarneiro** [aio-libs/aiojobs#66]
The documentation for Job.close() is very vague: https://aiojobs.readthedocs.io/en/stable/api.html#aiojobs.Job.close

```
coroutine close(*, timeout=None)
Close the job.

If timeout exceeded asyncio.TimeoutError raised.

The job is in closed state after finishing the method.
```

Yes, but what does "closing" a job really entail?  I suspect cancellation via asyncio.Task.cancel(), but the only way of knowing is to read the source code.

(goes read the source)

Yes, indeed it does `asyncio.Task.cancel()`.  That is good.  But docs need to be more specific.  Perhaps linking to the [asyncio docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel).

Suggestion of improved docstring:

```
Closes the job by means of requesting the underlying asyncio Task to be [cancelled](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel).
```

**Comment by Dreamsorcerer** [comment]
Happy to review a PR with a change to the docs.

**Comment by Dreamsorcerer** [comment]
I think I've improved this in #495.
